"""Create pallet table and other changes

Revision ID: 2f4d7818ddff
Revises: 3d6f79643bce
Create Date: 2025-04-12 00:11:24.094623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4d7818ddff'
down_revision: Union[str, None] = '3d6f79643bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('poster_pallet_id', sa.Integer(), nullable=True))
    op.drop_constraint('stories_poster_palette_id_fkey', 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'palettes', ['poster_pallet_id'], ['id'], ondelete='SET NULL')
    op.drop_column('stories', 'poster_palette_id')
    op.add_column('story_chapters', sa.Column('image_pallet_id', sa.Integer(), nullable=True))
    op.drop_constraint('story_chapters_image_palette_id_fkey', 'story_chapters', type_='foreignkey')
    op.create_foreign_key(None, 'story_chapters', 'palettes', ['image_pallet_id'], ['id'], ondelete='SET NULL')
    op.drop_column('story_chapters', 'image_palette_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_chapters', sa.Column('image_palette_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'story_chapters', type_='foreignkey')
    op.create_foreign_key('story_chapters_image_palette_id_fkey', 'story_chapters', 'palettes', ['image_palette_id'], ['id'], ondelete='SET NULL')
    op.drop_column('story_chapters', 'image_pallet_id')
    op.add_column('stories', sa.Column('poster_palette_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key('stories_poster_palette_id_fkey', 'stories', 'palettes', ['poster_palette_id'], ['id'], ondelete='SET NULL')
    op.drop_column('stories', 'poster_pallet_id')
    # ### end Alembic commands ###
