"""Create pallet table and other 

Revision ID: 5e27c5b65441
Revises: 01f97e9f841f
Create Date: 2025-04-11 23:58:06.190402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e27c5b65441'
down_revision: Union[str, None] = '01f97e9f841f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
