"""added gender and dob

Revision ID: 5f4fbbc3d538
Revises: 94ce27640264
Create Date: 2025-04-13 06:34:50.253585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4fbbc3d538'
down_revision: Union[str, None] = '94ce27640264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('gender', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Text(), nullable=True))

    # Optional: Set default values for existing rows if needed
    op.execute("UPDATE users SET gender = 'M' WHERE gender IS NULL")
    op.execute("UPDATE users SET dob = '2000-01-01' WHERE dob IS NULL")

    # Now make them NOT NULL
    op.alter_column('users', 'gender', nullable=False)
    op.alter_column('users', 'dob', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
