"""add created_at and tags to story and short_video

Revision ID: 6a298c3d598a
Revises: 7cd0162d8d27
Create Date: 2025-04-15 22:11:09.694161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a298c3d598a'
down_revision: Union[str, None] = '7cd0162d8d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_videos', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('short_videos', sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('stories', sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'tags')
    op.drop_column('short_videos', 'tags')
    op.drop_column('short_videos', 'created_at')
    # ### end Alembic commands ###
