"""add user views

Revision ID: 7cd0162d8d27
Revises: a6e31f0f5dec
Create Date: 2025-04-15 03:28:48.308183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd0162d8d27'
down_revision: Union[str, None] = 'a6e31f0f5dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('short_video_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['short_video_id'], ['short_videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('story_chapters', 'story_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_saves', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_saves', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('story_chapters', 'story_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('user_views')
    # ### end Alembic commands ###
