"""added gender and dob null true

Revision ID: c977ea6068f5
Revises: 5f4fbbc3d538
Create Date: 2025-04-13 06:39:40.391600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c977ea6068f5'
down_revision: Union[str, None] = '5f4fbbc3d538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'dob',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dob',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
